### ISSUE TITLE
Crystal selection

### ISSUE THREAD

**Issue by leonkiriliuk** [Kris-Sekula/NABU#1]
DJ Sures shared how the baud rate is generated in his latest video.  Here's the exact spot: https://youtu.be/wwaBKyNNwCw?t=79

Using the formula:  Baudrate = X hz crystal / 2 / 16

If we use the crystal you have here, X = 1843200 (1.8432 Mhz) results in baud rate of 57600.  Shouldn't we use a crystal that's exactly 2X to get 115200? Something like a  3.6864 Mhz? According to the video, the oem crystal is 3.5795 Mhz so this would mean over clocking.

**Comment by Kris-Sekula** [comment]
in the NABU computer the division by 2 happens before the clock reaches the serial chip ... so if you are feeding clock directly, you only need to divide by 16.
